name: Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    name: flake8-black-isort
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Flake8
        run: flake8 .

      - name: Check Black formatting
        run: black . --check

      - name: Check import order with isort
        run: isort . --check-only
